quantity = ["length","mass","time","electric current","thermodynamic temperature","amount of substance",
            "luminous intensity","displacement","area","volume","density","speed","acceleration","force",
            "energy","work","power","momentum","gravitational constant","plane angle","angular velocity",
            "angular acceleration","angular momentum","moment of inertia","inertia","torque","angular frequency",
            "frequency","period","youngs modulus","bulk modulus","shear modulus","surface tension","viscosity",
            "coefficient of viscosity","pressure","wavelength","intensity of wave","temperature","specific heat capacity",
            "stefens constant","heat","thermal conductivity","current","electromotive force","resistance","charge",
            "current density","electrical conductivity","dielectric constant","electric dipole moment","electric field",
            "potential","electric flux","capacitance","permittivity of space","permeability of space","magnetic field",
            "magnetic flux","magnetic dipole moment","inductance","solid angle","velocity","distance","emf"]
