quantity = ['acceleration', 'amount of substance', 'angular acceleration', 
'angular momentum', 'angular velocity', 'area', 'bulk modulus', 'capacitance', 
'charge', 'coefficient of viscosity', 'current', 'current density', 'density', 
'dielectric constant', 'displacement', 'distance', 'electric dipole moment', 
'electric field', 'electric flux', 'electrical conductivity', 'electromotive force', 
'emf', 'energy', 'flux', 'force', 'gravitational constant', 'heat', 'inductance', 
'inertiaangular frequency', 'intensity of wave', 'length', 'luminous intensity', 
'magnetic dipole moment', 'magnetic field', 'magnetic flux', 'mass', 'moment of inertia', 
'momentum', 'period', 'permeability', 'permittivity', 'plane angle', 'potential', 'power', 
'pressure', 'resistance', 'shear modulus', 'solid angle', 'specific heat capacity', 
'stefan constant', 'surface tension', 'temperature', 'thermal conductivity', 'time', 
'velocity', 'viscosity', 'voltage', 'volume', 'wavelength', 'work', 'young modulus']
